=== samanjahan/id2208_hw_1/src/java/Xml/company.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="companydata">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "company" minOccurs = "0" maxOccurs = "unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "orgNumber">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name = "companyInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name = "companyName" type="xs:string"/>
                                        <xs:element name = "industry" type="xs:string"/>
                                        <xs:element name="phoneNumber" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:length value="10"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name = "email" type="xs:string"/>
                                        <xs:element name = "ceo" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== samanjahan/id2208_hw_1/src/java/Xml/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE companydata>
<companydata
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="company.xsd">
    <company>
        <orgNumber>1223234590</orgNumber>
        <companyInfo>
            <companyName>Ntt</companyName>
            <industry>IT</industry>
            <phoneNumber>0894776455</phoneNumber>
            <email>ntt@info.se</email>
            <ceo>Alex</ceo>
        </companyInfo>
    </company>
    <company>
        <orgNumber>1223235551</orgNumber>
        <companyInfo>
            <companyName>Nokia</companyName>
            <industry>Mobile</industry>
            <phoneNumber>0894776499</phoneNumber>
            <email>nokia@info.se</email>
            <ceo>More</ceo>
        </companyInfo>
    </company>
</companydata>
