=== samanjahan/id2208_hw_1/src/java/Xml/transcript.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="transcript">
      <xs:complexType>
        <xs:sequence>
            <xs:element name="university" minOccurs = "0" maxOccurs = "unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="universityName" type="xs:string"/>
                        <xs:element name = "person" minOccurs = "0" maxOccurs = "unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="personName" type="xs:string"/>
                                        <xs:element name="ssn" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="10"/>
                                                    <xs:maxLength value="12"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    <xs:element name="degree" type="xs:string"/>
                                    <xs:element name="year" type="xs:int"/>
                                    <xs:element name = "courses">
                                        <xs:complexType>
                                            <xs:sequence minOccurs = "0" maxOccurs = "unbounded">
                                                <xs:element name = "course">
                                                    <xs:complexType>  
                                                        <xs:sequence>
                                                           <xs:element name = "name" type= "xs:string"/>
                                                           <xs:element name = "point">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:integer">
                                                                        <xs:minInclusive value="1"/>
                                                                        <xs:maxInclusive value="5"/>
                                                                    </xs:restriction>
                                                                 </xs:simpleType>
                                                           </xs:element>
                                                           <xs:element name = "id" type = "xs:string"/>
                                                        </xs:sequence>
                                                    </xs:complexType> 
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>  
        </xs:sequence>
      </xs:complexType>
    </xs:element> 
</xs:schema>

=== samanjahan/id2208_hw_1/src/java/Xml/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transcript>
<transcript 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="transcript.xsd">
    <university>
        <universityName>Kth</universityName>
        <person>
            <personName>Saman</personName>
            <ssn>8606261111</ssn>
            <degree>Datateknik</degree>
            <year>5</year>
            <courses>
                <course>
                    <name>Mate</name>
                    <point>5</point>
                    <id>id3333</id>
                </course>
                <course>
                    <name>Java</name>
                    <point>2</point>
                    <id>id2212</id>
                </course>     
            </courses>
        </person>
    </university>
    <university>
        <universityName>Su</universityName>
        <person>
            <personName>Alex</personName>
            <ssn>8309081111</ssn>
            <degree>Datateknik</degree>
            <year>5</year>
            <courses>
                <course>
                    <name>Matlab</name>
                    <point>3</point>
                    <id>id3333</id>
                </course>
                <course>
                    <name>C++</name>
                    <point>3</point>
                    <id>id2212</id>
                </course>     
            </courses>
        </person>
    </university>
</transcript>
